
#- Zero based ch number
ecmcEpicsEnvSetCalc("ECMC_LOOP_IDX_2_CHARS","${ECMC_LOOP_IDX=0}+1","%02x")

#- MTO inputs CH 1
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a0${ECMC_LOOP_IDX},0x60${ECMC_LOOP_IDX}0,0x01,U16,bo${ECMC_LOOP_IDX_2_CHARS}_status"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a0${ECMC_LOOP_IDX},0x60${ECMC_LOOP_IDX}0,0x011,U8,bo${ECMC_LOOP_IDX_2_CHARS}_outputOrderFB)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a0${ECMC_LOOP_IDX},0x60${ECMC_LOOP_IDX}0,0x012,U8,bo${ECMC_LOOP_IDX_2_CHARS}_eventsInBuffer)"
