
#- Zero based ch number
ecmcEpicsEnvSetCalc("ECMC_CH_ID_2_CHARS","${ECMC_LOOP_IDX=0}+1","%02x")
ecmcEpicsEnvSetCalc("ECMC_PDO_ID","8+(${ECMC_LOOP_IDX}*4)","%02x")
ecmcEpicsEnvSetCalc("ECMC_ENTRY_ID","8+(${ECMC_LOOP_IDX})","%02x")

#- MTO inputs CH 1
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x01,U8,bi${ECMC_CH_ID_2_CHARS}_eventCount)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x09,U8,bi${ECMC_CH_ID_2_CHARS}_status)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x11,U8,bi${ECMC_CH_ID_2_CHARS}_eventsInBuffer)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x12,U8,bi${ECMC_CH_ID_2_CHARS}_inputOrderFB)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x21,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventState)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x41,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime01)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x42,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime02)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x43,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime03)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x44,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime04)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x45,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime05)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x46,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime06)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x47,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime07)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x48,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime08)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x49,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime09)"
ecmcConfigOrDie "Cfg.EcAddEntryDT(${ECMC_EC_SLAVE_NUM},${ECMC_EC_VENDOR_ID},${ECMC_EC_PRODUCT_ID},2,3,0x1a${ECMC_PDO_ID},0x6${ECMC_ENTRY_ID}1,0x4A,U32,bi${ECMC_CH_ID_2_CHARS}_inputEventTime10)"
