#!/usr/bin/env python3

import argparse
import pathlib
import re
import sys


def normalize_ioc_name(raw: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "-", raw.strip()).strip("-")
    return cleaned.upper() or "CPP-LOGIC-IOC"


def parse_args():
    script_path = pathlib.Path(__file__).resolve()
    cpp_logic_root = script_path.parents[1]
    cfg_root = script_path.parents[5]
    default_ecmc = cfg_root.parent / "ecmc"

    parser = argparse.ArgumentParser(
        description="Scaffold a minimal IOC project for ecmc cpp_logic."
    )
    parser.add_argument("output_dir", help="Directory to create")
    parser.add_argument(
        "--ioc-name",
        help="IOC name used for startup/parameter filenames, default derived from output dir",
    )
    parser.add_argument(
        "--slave",
        default="14",
        help="EtherCAT slave number for the direct mapping example, default: 14",
    )
    parser.add_argument(
        "--cpp-logic-root",
        default=str(cpp_logic_root),
        help="Path to the cpp_logic example root, default: this script's repo area",
    )
    parser.add_argument(
        "--ecmc-root",
        default=str(default_ecmc),
        help="Path to ecmc checkout, default: sibling ../ecmc",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow writing into an existing non-empty directory",
    )
    return parser.parse_args()


def render(template: str, mapping: dict) -> str:
    rendered = template
    for key, value in mapping.items():
        rendered = rendered.replace(f"@{key}@", value)
    return rendered


TOP_MAKEFILE = """.PHONY: all install clean

IOC_STARTUP_FILE := $(notdir $(firstword $(wildcard *_startup.script)))
IOC_PARAMS_FILE := $(notdir $(firstword $(wildcard *_parameters.yaml)))
IOC_NAME ?= $(patsubst %_startup.script,%,$(IOC_STARTUP_FILE))
ifeq ($(IOC_NAME),)
IOC_NAME := $(patsubst %_parameters.yaml,%,$(IOC_PARAMS_FILE))
endif
CPP_LOGIC_ROOT ?= @CPP_LOGIC_ROOT@
PYTHON ?= python3
GENERATE_QT ?= 1
IOC_QT_PANEL := qt/$(IOC_NAME)_cpp_logic.ui
IOC_QTGEN := $(CPP_LOGIC_ROOT)/utils/cpp_logic_ioc_qtgen.py

all:
\t$(MAKE) -C src stage
\tif [ "$(GENERATE_QT)" = "1" ]; then $(PYTHON) $(IOC_QTGEN) --input cfg/libmain.so_cpp_logic.subs --output $(IOC_QT_PANEL) --pv-prefix "$(IOC_NAME):" --title "$(IOC_NAME) cpp_logic PVs"; fi

install: all
\tioc install --clean -V --ioc $(IOC_NAME)

clean:
\t$(MAKE) -C src clean
\t$(RM) $(IOC_QT_PANEL)
"""


STARTUP_SCRIPT = """# Generated by cpp_logic_new_ioc.py.
# This sample expects direct EL7041 PDO items:
#   ec0.s@SLAVE@.positionActual01
#   ec0.s@SLAVE@.driveControl01
#   ec0.s@SLAVE@.velocitySetpoint01
#
# Useful panels after startup:
#   caqtdm -macro "IOC=@IOC_NAME@" $(ecmccfg_DIR)qt/ecmcCppLogicOverview.ui
#   caqtdm -macro "IOC=@IOC_NAME@,CPP_ID=0" $(ecmccfg_DIR)qt/ecmcCppLogic.ui
#   caqtdm qt/@IOC_NAME@_cpp_logic.ui

require ecmccfg "ECMC_VER=struc"
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=@SLAVE@,HW_DESC=EL7041-0052"
${SCRIPTEXEC} ${ecmccfg_DIR}applyComponent.cmd, "COMP=Motor-Generic-2Phase-Stepper,MACROS='I_MAX_MA=500,I_STDBY_MA=200,U_NOM_MV=48000,R_COIL_MOHM=1230'"
${SCRIPTEXEC} ${ecmccfg_DIR}scripts/loadCppLogic.cmd, "REPORT=1"
"""


PARAMETERS_YAML = """ioc_name: @IOC_NAME@
ioc_host: c6025a-08
ioc_port: 50001
ioc_user: root
epics_version: 7.0.10
os: deb12
cpu_architecture: x86_64
"""


IOC_README = """# `@IOC_NAME@`

Generated by `cpp_logic_new_ioc.py` as a minimal IOC project for the additive
`cpp_logic` interface in `ecmc`.

The generated tree is intentionally small:

- `src/main.cpp`
- `src/Makefile`
- `@IOC_NAME@_startup.script`
- `@IOC_NAME@_parameters.yaml`

Expected flow:

1. `make`
2. `ioc install --clean -V --ioc @IOC_NAME@`
3. start the IOC with `@IOC_NAME@_startup.script`

The build stages:

- `bin/main.so`
- `cfg/libmain.so_cpp_logic.subs`
- `qt/@IOC_NAME@_cpp_logic.ui`

The startup script uses the defaults from `loadCppLogic.cmd`, so it
automatically loads:

- `bin/main.so`
- `cfg/libmain.so_cpp_logic.subs`

The generated panel is IOC-local:

```sh
caqtdm qt/@IOC_NAME@_cpp_logic.ui
```
"""


SRC_MAKEFILE = """PROGRAM := main
CPP_LOGIC_ROOT ?= @CPP_LOGIC_ROOT@
ECMC ?= @ECMC_ROOT@
include $(CPP_LOGIC_ROOT)/utils/cpp_logic_ioc.make
"""


CPP_SOURCE = """/*************************************************************************\\
* Copyright (c) 2026 Paul Scherrer Institute
* ecmc is distributed subject to a Software License Agreement found
* in file LICENSE that is included with this distribution.
*
*  main.cpp
*
*  Starter example for the additive C++ logic interface in ecmc.
*
\\*************************************************************************/

#include "ecmcCppLogic.hpp"

struct CppLogicStarter : public ecmcCpp::LogicBase {
  int32_t actual_position {0};
  int16_t drive_control {0};
  int16_t velocity_setpoint {1000};

  CppLogicStarter() {
    ecmc.input("ec.s@SLAVE@.positionActual01", actual_position)
        .output("ec.s@SLAVE@.driveControl01", drive_control)
        .output("ec.s@SLAVE@.velocitySetpoint01", velocity_setpoint);

    epics.readOnly("starter.actual_position", actual_position)
         .writable("starter.velocity_setpoint", velocity_setpoint);
  }

  void run() override {
    drive_control = 0x0001;
  }
};

ECMC_CPP_LOGIC_REGISTER_DEFAULT(CppLogicStarter)
"""


def write_text(path: pathlib.Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main():
    args = parse_args()
    output_dir = pathlib.Path(args.output_dir).resolve()
    if output_dir.exists() and any(output_dir.iterdir()) and not args.force:
        raise RuntimeError(
            f"{output_dir} already exists and is not empty; rerun with --force to overwrite files"
        )

    ioc_name = normalize_ioc_name(args.ioc_name or output_dir.name)
    mapping = {
        "IOC_NAME": ioc_name,
        "CPP_LOGIC_ROOT": str(pathlib.Path(args.cpp_logic_root).resolve()),
        "ECMC_ROOT": str(pathlib.Path(args.ecmc_root).resolve()),
        "SLAVE": str(args.slave),
    }

    write_text(output_dir / "Makefile", render(TOP_MAKEFILE, mapping))
    write_text(output_dir / f"{ioc_name}_startup.script", render(STARTUP_SCRIPT, mapping))
    write_text(output_dir / f"{ioc_name}_parameters.yaml", render(PARAMETERS_YAML, mapping))
    write_text(output_dir / "README.md", render(IOC_README, mapping))
    write_text(output_dir / "src" / "Makefile", render(SRC_MAKEFILE, mapping))
    write_text(output_dir / "src" / "main.cpp", render(CPP_SOURCE, mapping))

    print(f"Created IOC scaffold in {output_dir}")


if __name__ == "__main__":
    try:
        main()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
