
require ecmccfg sandst_a "MASTER_ID=0, ECMC_VER=sandst_a"

require ecmc_cpp_logic_as_module sandst_a 
${SCRIPTEXEC} ${ecmc_cpp_logic_as_module_DIR}addSlaveAndCPPModule.cmd "ASYN_PORT=MY_PORT_28,S_ID=28"
${SCRIPTEXEC} ${ecmc_cpp_logic_as_module_DIR}addSlaveAndCPPModule.cmd "ASYN_PORT=MY_PORT_29,S_ID=29"
${SCRIPTEXEC} ${ecmc_cpp_logic_as_module_DIR}addSlaveAndCPPModule.cmd "ASYN_PORT=MY_PORT_30,S_ID=30"
