#==============================================================================
# loadNativeLogic.cmd
#- Arguments: [FILE], [LOGIC_ID], [ASYN_PORT], [SAMPLE_RATE_MS], [LOAD_DEFAULT_PVS], [LOAD_APP_PVS], [EPICS_SUBST], [DB_PREFIX], [DB_MACROS], [REPORT]

#-d /**
#-d   \brief Script for loading a native C/C++ logic shared library in ecmc.
#-d   \details Loads one native logic instance, then optionally loads the
#-d            built-in core substitutions and one custom substitutions file
#-d            for the user-defined `epics.*` exports.
#-d   \author Anders Sandström, OpenAI Codex
#-d   \file
#-d   \param FILE      Shared library implementing ecmc_native_logic_get_api(),
#-d                  default `bin/main.so`.
#-d   \param LOGIC_ID  Native logic instance index, default 0.
#-d   \param ASYN_PORT Optional dedicated asyn port, default NATIVE.LOGIC<LOGIC_ID>.
#-d   \param SAMPLE_RATE_MS Optional execution rate in milliseconds.
#-d   \param LOAD_DEFAULT_PVS Load built-in control/status PVs, default 1.
#-d   \param LOAD_APP_PVS Load custom EPICS substitutions for `epics.*` exports, default 0.
#-d   \param EPICS_SUBST Optional custom substitutions file, default ${FILE}.substitutions.
#-d   \param DB_PREFIX Optional record prefix, default ${IOC}:.
#-d   \param DB_MACROS Optional extra dbLoadTemplate macros.
#-d   \param REPORT    Print loaded native logic report if >0, default 1.
#-d */

epicsEnvSet("ECMC_NATIVE_LOGIC_ID", "${LOGIC_ID=0}")
epicsEnvSet("ECMC_NATIVE_LOGIC_FILE", "${FILE=bin/main.so}")

ecmcIf("'${ASYN_PORT=EMPTY}'='EMPTY'",ECMC_NATIVE_LOGIC_PORT_EMPTY_TRUE,ECMC_NATIVE_LOGIC_PORT_EMPTY_FALSE)
${ECMC_NATIVE_LOGIC_PORT_EMPTY_TRUE}epicsEnvSet("ECMC_NATIVE_LOGIC_PORT", "NATIVE.LOGIC${ECMC_NATIVE_LOGIC_ID}")
#else
${ECMC_NATIVE_LOGIC_PORT_EMPTY_FALSE}epicsEnvSet("ECMC_NATIVE_LOGIC_PORT", "${ASYN_PORT}")
ecmcEndIf(ECMC_NATIVE_LOGIC_PORT_EMPTY_TRUE,ECMC_NATIVE_LOGIC_PORT_EMPTY_FALSE)

epicsEnvSet("ECMC_NATIVE_LOGIC_CONFIG", "asyn_port=${ECMC_NATIVE_LOGIC_PORT};sample_rate_ms=${SAMPLE_RATE_MS=}")
epicsEnvSet("ECMC_NATIVE_LOGIC_CORE_EPICS_SUBST", "${ecmccfg_DIR}db/generic/ecmcNativeLogicCore.substitutions")
epicsEnvSet("ECMC_NATIVE_LOGIC_DB_MACROS_BASE", "P=${DB_PREFIX=$(IOC):},PORT=${ECMC_NATIVE_LOGIC_PORT},NLG_ID=${ECMC_NATIVE_LOGIC_ID}")
epicsEnvSet("ECMC_NATIVE_LOGIC_DEFAULT_EPICS_SUBST", "${ECMC_NATIVE_LOGIC_FILE}.substitutions")

ecmcFileExist("${ECMC_NATIVE_LOGIC_FILE}",1)
ecmcConfigOrDie "Cfg.LoadNativeLogic(${ECMC_NATIVE_LOGIC_ID},${ECMC_NATIVE_LOGIC_FILE},${ECMC_NATIVE_LOGIC_CONFIG})"

ecmcEpicsEnvSetCalcTernary("ECMC_NATIVE_LOGIC_REPORT", "${REPORT=1}>0", "", "#")
${ECMC_NATIVE_LOGIC_REPORT}ecmcConfigOrDie "Cfg.ReportNativeLogic(${ECMC_NATIVE_LOGIC_ID})"
epicsEnvUnset(ECMC_NATIVE_LOGIC_REPORT)

ecmcIf("'${LOAD_DEFAULT_PVS=1}'='0'",NATIVE_LOGIC_CORE_SKIP_TRUE,NATIVE_LOGIC_CORE_SKIP_FALSE)
# skip built-in native logic control/status PVs
#else
  ${NATIVE_LOGIC_CORE_SKIP_FALSE}ecmcIf("'${DB_MACROS=EMPTY}'='EMPTY'",NATIVE_LOGIC_CORE_DB_EMPTY_TRUE,NATIVE_LOGIC_CORE_DB_EMPTY_FALSE)
  ${NATIVE_LOGIC_CORE_SKIP_FALSE}${NATIVE_LOGIC_CORE_DB_EMPTY_TRUE}dbLoadTemplate("${ECMC_NATIVE_LOGIC_CORE_EPICS_SUBST}", "${ECMC_NATIVE_LOGIC_DB_MACROS_BASE}")
  #else
  ${NATIVE_LOGIC_CORE_SKIP_FALSE}${NATIVE_LOGIC_CORE_DB_EMPTY_FALSE}dbLoadTemplate("${ECMC_NATIVE_LOGIC_CORE_EPICS_SUBST}", "${ECMC_NATIVE_LOGIC_DB_MACROS_BASE},${DB_MACROS}")
  ${NATIVE_LOGIC_CORE_SKIP_FALSE}ecmcEndIf(NATIVE_LOGIC_CORE_DB_EMPTY_TRUE,NATIVE_LOGIC_CORE_DB_EMPTY_FALSE)
ecmcEndIf(NATIVE_LOGIC_CORE_SKIP_TRUE,NATIVE_LOGIC_CORE_SKIP_FALSE)

ecmcIf("'${LOAD_APP_PVS=0}'='0'",NATIVE_LOGIC_APP_SKIP_TRUE,NATIVE_LOGIC_APP_SKIP_FALSE)
# skip generated app PVs
#else
  ${NATIVE_LOGIC_APP_SKIP_FALSE}ecmcIf("'${EPICS_SUBST=EMPTY}'='EMPTY'",NATIVE_LOGIC_APP_SUBST_EMPTY_TRUE,NATIVE_LOGIC_APP_SUBST_EMPTY_FALSE)
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_TRUE}ecmcFileExist("${ECMC_NATIVE_LOGIC_DEFAULT_EPICS_SUBST}",1,1)
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_TRUE}ecmcIf("'${DB_MACROS=EMPTY}'='EMPTY'",NATIVE_LOGIC_APP_DB_EMPTY_TRUE_1,NATIVE_LOGIC_APP_DB_EMPTY_FALSE_1)
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_TRUE}${NATIVE_LOGIC_APP_DB_EMPTY_TRUE_1}dbLoadTemplate("${ECMC_NATIVE_LOGIC_DEFAULT_EPICS_SUBST}", "${ECMC_NATIVE_LOGIC_DB_MACROS_BASE}")
  #else
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_TRUE}${NATIVE_LOGIC_APP_DB_EMPTY_FALSE_1}dbLoadTemplate("${ECMC_NATIVE_LOGIC_DEFAULT_EPICS_SUBST}", "${ECMC_NATIVE_LOGIC_DB_MACROS_BASE},${DB_MACROS}")
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_TRUE}ecmcEndIf(NATIVE_LOGIC_APP_DB_EMPTY_TRUE_1,NATIVE_LOGIC_APP_DB_EMPTY_FALSE_1)
#else
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_FALSE}ecmcFileExist("${EPICS_SUBST}",1,1)
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_FALSE}ecmcIf("'${DB_MACROS=EMPTY}'='EMPTY'",NATIVE_LOGIC_APP_DB_EMPTY_TRUE_2,NATIVE_LOGIC_APP_DB_EMPTY_FALSE_2)
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_FALSE}${NATIVE_LOGIC_APP_DB_EMPTY_TRUE_2}dbLoadTemplate("${EPICS_SUBST}", "${ECMC_NATIVE_LOGIC_DB_MACROS_BASE}")
  #else
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_FALSE}${NATIVE_LOGIC_APP_DB_EMPTY_FALSE_2}dbLoadTemplate("${EPICS_SUBST}", "${ECMC_NATIVE_LOGIC_DB_MACROS_BASE},${DB_MACROS}")
  ${NATIVE_LOGIC_APP_SKIP_FALSE}${NATIVE_LOGIC_APP_SUBST_EMPTY_FALSE}ecmcEndIf(NATIVE_LOGIC_APP_DB_EMPTY_TRUE_2,NATIVE_LOGIC_APP_DB_EMPTY_FALSE_2)
  ${NATIVE_LOGIC_APP_SKIP_FALSE}ecmcEndIf(NATIVE_LOGIC_APP_SUBST_EMPTY_TRUE,NATIVE_LOGIC_APP_SUBST_EMPTY_FALSE)
ecmcEndIf(NATIVE_LOGIC_APP_SKIP_TRUE,NATIVE_LOGIC_APP_SKIP_FALSE)
